### ISSUE TITLE
Python 3?

### ISSUE THREAD

**Issue by MissPhilbin** [pimoroni/explorer-hat#3]
Instructions are for Python 2 and do not include Python 3. Would be useful for all users if both were included. Many thanks.

**Comment by Gadgetoid** [comment]
To my knowledge there's still no Python 3 compatible smbus module in Raspbian, so Explorer HAT wont work with Python 3.

On the Basic the Inputs/Outputs would work, but the cap touch wouldn't, so it would just be confusing to have Python 3 instructions that result in a partially working board.

When we finally get a Python 3 smbus, we'll have to run back through our lineup, make sure it actually does work, and update the software/instructions as necessary.

**Comment by MissPhilbin** [comment]
It was my understanding that python3 smbus was being dealt with. My bad. I've pinged members of the PSF to help.

**Comment by Gadgetoid** [comment]
Thank you! It was my understanding also, but it's been a long time in the works!

**Comment by bennuttall** [comment]
This can be closed, right?

**Comment by Gadgetoid** [comment]
Yup!
