### ISSUE TITLE
Open Source Hardware

### ISSUE THREAD

**Issue by ARKopp** [pimoroni/explorer-hat#33]
is the hardware opensource as well?

**Comment by Gadgetoid** [comment]
Nope. Propeller HAT is our only OSHW board: https://github.com/pimoroni/propeller-hat/tree/master/hardware

**Comment by ARKopp** [comment]
ok thanks. why?

**Comment by Gadgetoid** [comment]
It leaves us wide open to a market of third-party clones.

We prefer to double down on excellent software and support, helping people where we can.

**Comment by ARKopp** [comment]
when they want to clone you they clone you. This is actually good
marketing. I think your customers will by from you and not the clones.

I can also copy your schematics and puplish the plans. I thought you want
to become the europe adafruit. A big part is that you also

do openhardware and share freely and let people change your designs.
