### ISSUE TITLE
Function Reference: analog read() returns Volts not Millivolts

### ISSUE THREAD

**Issue by thymjan** [pimoroni/explorer-hat#35]
The resolution seems to be something like one Millivolt, but the unit must be Volts (e.g. 3.142 V).
Either the unit of threshold is Volts (default 0.1V)

```
from explorerhat import analog

def battStatusReport(analog, value):
    Print("Battery voltage changed to {}V".format(value))

analog.one.changed(battStatusReport, 0.45)
```

**Comment by Gadgetoid** [comment]
Good spot. You are correct of course. I have updated the documentation to reflect that all values are given or should be given in volts.

I'm a little rusty, but it's an 11bit ADC (the 12th bit is the sign bit for negative readings in differential mode) with a full scale range of 6.144mV. That's `(6144/2048) = 3`, or 3millivolts per division. So to add to this, 0.003 is the smallest possible detectable change.
