### ISSUE TITLE
explorerhat.touch.is_held() is sleeping on the job :)

### ISSUE THREAD

**Issue by snobu** [pimoroni/explorer-hat#40]
```sh
$ python3
Python 3.5.3 (default, Jan 19 2017, 14:11:04)
[GCC 6.3.0 20170124] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import explorerhat
Explorer HAT Pro detected...
>>> while 1: explorerhat.touch.is_held()['one']
...
False
False
False
False
.... // hold touch ONE
False
False
False
.... // keep holding touch ONE
False
False
False
// False forever
```
Same deal with Python2, so not a 2/3 quirk.

_Am i holding it wrong_? How do i get a long touch event without doing some delta between pressed and released on my own? Because .. i mean.. the best code is somebody else's code.

It's really not a problem for me to implement that but i'm just curious if `is_held()` is broken or i'm being silly.

**Comment by Gadgetoid** [comment]
It's quite likely that the code is broken somehow. I can't recall if it tries to maintain some internal state (using pressed/released in much the same way as you mention) or if it reads the "held" status directly from the captouch chip (which IIRC is a feature of the chip, albeit one that directly conflicts with its re-calibrate-if-pad-is-held-for-too-long feature).

I shall have to look into it!
