### ISSUE TITLE
Documentation: Explorer hat inputs are not quite the same as pi ones

### ISSUE THREAD

**Issue by KimSJ** [pimoroni/explorer-hat#44]
The Pi pins can have a soft pull-up enabled, ExplorerHat ones can't; they always(?) read as 0/False when unconnected. It would be helpful to mention this minor difference.

**Comment by Gadgetoid** [comment]
I've updated the technical reference with some notes about pull up/down resistors. Thank you!

It looks like the buffer chip clamps down to 0v for anything less than 1.7v input.
