### ISSUE TITLE
Python wants me to check my ic2 settings

### ISSUE THREAD

**Issue by Matlex2831** [pimoroni/explorer-hat#46]

**Comment by Matlex2831** [comment]
I definitely have ic2 enabled

**Comment by Matlex2831** [comment]
pls help quick i have to run a club on monday

**Comment by Gadgetoid** [comment]
Could you elaborate, please?

The steps you took to encounter your problem and a screen cap or copy & paste of the error output would be helpful. Additionally a capture of the output from `i2cdetect -y 1` may also help.
