### ISSUE TITLE
Please check your i2c settings!

### ISSUE THREAD

**Issue by Sjosvard122** [pimoroni/explorer-hat#48]
Hey having the problem with i2c and have tried to follow most of the guides i've found on the internet. My raspberry crashed so i hade to reset all my work on the selfdriving car i've  done for a school prodject. Last time I hade the same problem and my teacher replace a file from github in the terminal.  Please help med :)

**Comment by Gadgetoid** [comment]
Added some instructions to the README for enabling i2c.
